CREATE TABLE `exercises` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text,
	`name` text NOT NULL,
	`muscle_group` text,
	`equipment` text DEFAULT 'other' NOT NULL,
	`is_custom` integer DEFAULT false NOT NULL,
	`canonical_exercise_id` text,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`canonical_exercise_id`) REFERENCES `exercises`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE INDEX `exercises_user_id_idx` ON `exercises` (`user_id`);--> statement-breakpoint
CREATE INDEX `exercises_equipment_idx` ON `exercises` (`equipment`);--> statement-breakpoint
-- Seed catalogo globale (SPEC Appendix A). user_id NULL = globale; is_custom 0.
INSERT INTO `exercises` (`id`, `user_id`, `name`, `muscle_group`, `equipment`, `is_custom`) VALUES
('ex_leg_press', NULL, 'Leg Press', 'Quadricipiti / Glutei', 'machine', 0),
('ex_hack_squat', NULL, 'Hack Squat', 'Quadricipiti / Glutei', 'machine', 0),
('ex_leg_extension', NULL, 'Leg Extension', 'Quadricipiti', 'machine', 0),
('ex_leg_curl', NULL, 'Leg Curl (seduto / sdraiato)', 'Femorali', 'machine', 0),
('ex_calf_raise_machine', NULL, 'Calf Raise (macchina)', 'Polpacci', 'machine', 0),
('ex_hip_abduction', NULL, 'Hip Abduction (abduttori)', 'Abduttori / Glutei', 'machine', 0),
('ex_hip_adduction', NULL, 'Hip Adduction (adduttori)', 'Adduttori', 'machine', 0),
('ex_chest_press', NULL, 'Chest Press', 'Pettorali', 'machine', 0),
('ex_pec_deck', NULL, 'Pectoral / Pec Deck', 'Pettorali', 'machine', 0),
('ex_shoulder_press_machine', NULL, 'Shoulder Press', 'Spalle', 'machine', 0),
('ex_reverse_fly_machine', NULL, 'Reverse Fly (macchina)', 'Deltoidi posteriori', 'machine', 0),
('ex_lat_pulldown', NULL, 'Lat Machine / Lat Pulldown', 'Dorsali', 'machine', 0),
('ex_vertical_traction', NULL, 'Vertical Traction', 'Dorsali', 'machine', 0),
('ex_seated_row_machine', NULL, 'Seated Row (pulley)', 'Dorsali / Schiena', 'machine', 0),
('ex_biceps_curl_machine', NULL, 'Biceps Curl (macchina)', 'Bicipiti', 'machine', 0),
('ex_triceps_extension_machine', NULL, 'Triceps Extension (macchina)', 'Tricipiti', 'machine', 0),
('ex_back_extension_machine', NULL, 'Back Extension (lombare)', 'Lombari', 'machine', 0),
('ex_abdominal_crunch_machine', NULL, 'Abdominal Crunch (macchina)', 'Addominali / Core', 'machine', 0),
('ex_squat', NULL, 'Squat', 'Quadricipiti / Glutei', 'barbell', 0),
('ex_front_squat', NULL, 'Front Squat', 'Quadricipiti', 'barbell', 0),
('ex_deadlift', NULL, 'Stacco da terra (Deadlift)', 'Catena posteriore / Schiena', 'barbell', 0),
('ex_romanian_deadlift', NULL, 'Stacco rumeno (Romanian Deadlift)', 'Femorali / Glutei', 'barbell', 0),
('ex_hip_thrust', NULL, 'Hip Thrust', 'Glutei', 'barbell', 0),
('ex_barbell_lunge', NULL, 'Affondi con bilanciere', 'Quadricipiti / Glutei', 'barbell', 0),
('ex_bench_press', NULL, 'Panca piana', 'Pettorali', 'barbell', 0),
('ex_incline_bench_press', NULL, 'Panca inclinata', 'Pettorali alti', 'barbell', 0),
('ex_decline_bench_press', NULL, 'Panca declinata', 'Pettorali bassi', 'barbell', 0),
('ex_military_press', NULL, 'Military Press / Lento avanti', 'Spalle', 'barbell', 0),
('ex_barbell_row', NULL, 'Rematore con bilanciere', 'Dorsali', 'barbell', 0),
('ex_barbell_curl', NULL, 'Curl con bilanciere', 'Bicipiti', 'barbell', 0),
('ex_skull_crusher', NULL, 'French Press / Skull Crusher', 'Tricipiti', 'barbell', 0),
('ex_dumbbell_bench_press', NULL, 'Panca piana con manubri', 'Pettorali', 'dumbbell', 0),
('ex_incline_dumbbell_press', NULL, 'Panca inclinata con manubri', 'Pettorali alti', 'dumbbell', 0),
('ex_dumbbell_fly', NULL, 'Croci su panca', 'Pettorali', 'dumbbell', 0),
('ex_dumbbell_shoulder_press', NULL, 'Lento avanti con manubri', 'Spalle', 'dumbbell', 0),
('ex_lateral_raise', NULL, 'Alzate laterali', 'Deltoidi laterali', 'dumbbell', 0),
('ex_front_raise', NULL, 'Alzate frontali', 'Deltoidi anteriori', 'dumbbell', 0),
('ex_one_arm_dumbbell_row', NULL, 'Rematore con manubrio (1 braccio)', 'Dorsali', 'dumbbell', 0),
('ex_dumbbell_curl', NULL, 'Curl con manubri', 'Bicipiti', 'dumbbell', 0),
('ex_hammer_curl', NULL, 'Curl a martello (Hammer)', 'Bicipiti / Brachiale', 'dumbbell', 0),
('ex_dumbbell_triceps_extension', NULL, 'French press con manubrio', 'Tricipiti', 'dumbbell', 0),
('ex_dumbbell_lunge', NULL, 'Affondi con manubri', 'Quadricipiti / Glutei', 'dumbbell', 0),
('ex_dumbbell_romanian_deadlift', NULL, 'Stacco rumeno con manubri', 'Femorali / Glutei', 'dumbbell', 0),
('ex_cable_crossover', NULL, 'Croci ai cavi (Cable Crossover)', 'Pettorali', 'cable', 0),
('ex_cable_lat_pulldown', NULL, 'Lat pulldown ai cavi', 'Dorsali', 'cable', 0),
('ex_cable_row', NULL, 'Pulley basso (Cable Row)', 'Dorsali / Schiena', 'cable', 0),
('ex_face_pull', NULL, 'Face Pull', 'Deltoidi posteriori', 'cable', 0),
('ex_cable_pushdown', NULL, 'Pushdown ai cavi', 'Tricipiti', 'cable', 0),
('ex_cable_curl', NULL, 'Curl ai cavi', 'Bicipiti', 'cable', 0),
('ex_cable_crunch', NULL, 'Crunch ai cavi', 'Addominali / Core', 'cable', 0),
('ex_pull_up', NULL, 'Trazioni (Pull-up)', 'Dorsali', 'bodyweight', 0),
('ex_chin_up', NULL, 'Trazioni presa inversa (Chin-up)', 'Dorsali / Bicipiti', 'bodyweight', 0),
('ex_dip', NULL, 'Dip alle parallele', 'Pettorali / Tricipiti', 'bodyweight', 0),
('ex_push_up', NULL, 'Piegamenti (Push-up)', 'Pettorali', 'bodyweight', 0),
('ex_bodyweight_squat', NULL, 'Squat a corpo libero', 'Quadricipiti / Glutei', 'bodyweight', 0),
('ex_bodyweight_lunge', NULL, 'Affondi', 'Quadricipiti / Glutei', 'bodyweight', 0),
('ex_hyperextension', NULL, 'Hyperextension', 'Lombari', 'bodyweight', 0),
('ex_plank', NULL, 'Plank', 'Core', 'bodyweight', 0),
('ex_crunch', NULL, 'Crunch', 'Addominali', 'bodyweight', 0),
('ex_bodyweight_calf_raise', NULL, 'Calf Raise a corpo libero', 'Polpacci', 'bodyweight', 0);